style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kohirens/tmpl-aws-website
options:
  commits:
     filters:
       Type:
         - add
         - chg
         - dep
         - doc
         - fix
         - rft
         - rmv
  commit_groups:
     title_maps:
       add: Added
       chg: Changed
       doc: Documented
       dep: Deprecated
       fix: Fixed
       rft: Refactored
       rmv: Removed
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE